name: adopet
description: Aplicativo Android de adoção de pets.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^21.0.0
  image_picker: ^1.2.1
  shared_preferences: ^2.5.3

flutter:
  uses-material-design: true
